version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

  faiss:
    build:
      context: ./services/faiss
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      INDEX_PATH: /app/index/support.idx
      EMB_PATH: /app/embeddings.jsonl
    volumes:
      - ./services/faiss:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
